export const ADD_TODO = 'ADD_TODO'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const TOGGLE_HIDE_COMPLETED = 'TOGGLE_HIDE_COMPLETED'
export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO'